apiVersion: apps/v1
kind: Deployment
metadata:
  name: petshop-deployment
  labels:
    app: app1-petshop
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app1-petshop
  template:
    metadata:
      labels:
        app: app1-petshop
    spec:
      containers:
        - name: app1-petshop
          image: chinnayya339/petshop-1:v3.3.0
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: petshop-loadbalancer-service
  labels:
    app: app1-petshop
spec:
  type: LoadBalancer
  selector:
    app: app1-petshop
  ports:
    - port: 8080
      targetPort: 8080
